title:              Computer security and related topics
email:              jaydenkaiorivers@gmail.com
description:        Writings on vulnerability research and exploitation
author:             Awarau
baseurl:            "/"
url:                "https://ruia-ruia.github.io"

# Social Profiles
twitter_username:   Awarau1
github_username:    ruia-ruia

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

title_image: '/img/posts/cve-2022-29582/meta-caterpillar-even-more-hungry.jpg'

# Build settings
# Dependencies
markdown:         kramdown

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..6


paginate: 1

# Permalinks
permalink:        pretty
paginate_path:      "/posts/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
  - jekyll-toc